### ISSUE TITLE
IDE and Workspace chat

### ISSUE THREAD

**Issue by ProfYaffle88** [ProfYaffle88/project-art-portfolio#9]
Chat about how we're going to branch and work.

**Comment by Graciete-Gil** [comment]
Hi team maybe we could do like this:.
Order of Changes:
Give a unique number to each change within a specific element.

Example: Head-LogoUpdate-1=> Head-LogoUpdate-2...
 Head-ColorSchemeChange-2 ,=>Head-ColorSchemeChange-3...
 Body- Paragraph(name of Paragraph)-TextModification-1, 
 Body-ImageSwap-2; ...
 Footer-ContactInfoUpdate-1,...
 Footer-SocialMediaLinksChange-2,... 
and so on.
